apiVersion: v1
kind: Namespace
metadata:
  name: velya-security
  labels:
    app.kubernetes.io/part-of: velya-platform
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
