apiVersion: v1
kind: LimitRange
metadata:
  name: web-defaults
  namespace: velya-dev-web
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: core-defaults
  namespace: velya-dev-core
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 150m
        memory: 192Mi
      default:
        cpu: 750m
        memory: 768Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: platform-defaults
  namespace: velya-dev-platform
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
