apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: velya-base

commonLabels:
  app.kubernetes.io/part-of: velya-platform
  app.kubernetes.io/managed-by: kustomize

resources:
  - ../../../infra/bootstrap/namespaces/dev.yaml
  - ../../../infra/bootstrap/policies/network-policy-default-deny.yaml
  - ../../../infra/bootstrap/policies/resource-quotas-dev.yaml
  - ../../../infra/bootstrap/policies/limit-ranges-dev.yaml
