export type Product = "hospitalar" | "lince" | "shared";

export interface EngineeringAgent {
  id: string;
  name: string;
  description: string;
  officeId: string;
  source: "engineering" | "opensquad" | "executive";
  /** Produto ao qual o agent serve primariamente. "shared" = serve aos dois sem misturar contexto. */
  product: Product;
  /** Nome completo em pt-BR (gerado automaticamente quando não há mapping manual). */
  displayName?: string;
  /** Cargo em pt-BR. */
  role?: string;
  /** Descrição em pt-BR. */
  descriptionPtBr?: string;
  /** Posicionamento como liderança: ceo, conselheiro, gerente, coordenador, supervisor. */
  leadership?: "ceo" | "conselheiro" | "gerente" | "coordenador" | "supervisor" | null;
  gender?: "m" | "f";
  autoGenerated?: boolean;
}

export interface Office {
  id: string;
  name: string;
  description: string;
  hierarchy: "executive" | "council" | "office" | "squad-ala";
  product: Product;
  reportsTo: string | null;
  agents: EngineeringAgent[];
}

export interface CompanyMapData {
  offices: Office[];
  updatedAt: string;
}
