# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "velya-dev-tfstate"
    dynamodb_table = "velya-dev-tflock"
    encrypt        = true
    key            = "dev/wazuh-server/terraform.tfstate"
    region         = "us-east-1"
  }
}
