# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "lince-tfstate-582381607124-us-east-1"
    dynamodb_table = "lince-tfstate-lock"
    encrypt        = true
    key            = "dev/iam-admin-switch-role/terraform.tfstate"
    kms_key_id     = "arn:aws:kms:us-east-1:582381607124:key/3294d44a-bbe2-4c7f-906d-4b38cfe0a15b"
    region         = "us-east-1"
  }
}
