# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.4"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.80"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  allowed_account_ids = ["582381607124"]

  default_tags {
    tags = {
      Project      = "lince"
      Environment  = "dev"
      ManagedBy    = "opentofu"
      Orchestrator = "terragrunt"
    }
  }
}
