/**
 * Task priority levels, ordered from lowest to highest urgency.
 */
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Task lifecycle status.
 */
export type TaskStatus =
  | 'pending'
  | 'in-progress'
  | 'completed'
  | 'cancelled'
  | 'escalated';

/**
 * How the task was originated.
 */
export type TaskSource =
  | 'system'
  | 'ai-suggestion'
  | 'manual'
  | 'integration'
  | 'workflow';

/**
 * Audit trail entry recording a state change on a task.
 */
export interface TaskAuditEntry {
  /** Unique ID for this audit entry. */
  readonly id: string;

  /** ISO-8601 timestamp of the action. */
  readonly timestamp: string;

  /** User or system that performed the action. */
  readonly actor: string;

  /** Action taken. */
  readonly action: TaskAuditAction;

  /** Previous value, if applicable. */
  readonly previousValue: string | null;

  /** New value, if applicable. */
  readonly newValue: string | null;

  /** Optional note or rationale. */
  readonly note: string | null;
}

/**
 * Enumerated audit actions for tasks.
 */
export type TaskAuditAction =
  | 'created'
  | 'assigned'
  | 'reassigned'
  | 'status_changed'
  | 'priority_changed'
  | 'escalated'
  | 'completed'
  | 'cancelled'
  | 'note_added'
  | 'due_date_changed';

/**
 * Task entity representing an actionable work item in the clinical inbox.
 *
 * Tasks can be created manually by staff, generated by AI agents,
 * triggered by system rules, or received from external integrations.
 * They support parent-child hierarchies for complex workflows.
 */
export interface Task {
  /** Unique task identifier. */
  readonly id: string;

  /** Short, actionable title. */
  readonly title: string;

  /** Detailed description of the work to be done. */
  readonly description: string;

  /** Patient this task relates to, null for non-patient tasks. */
  readonly patientId: string | null;

  /** Encounter this task relates to, null for non-encounter tasks. */
  readonly encounterId: string | null;

  /** Priority determines sort order and notification urgency. */
  readonly priority: TaskPriority;

  /** Current lifecycle status. */
  readonly status: TaskStatus;

  /** How this task was created. */
  readonly source: TaskSource;

  /** Category for routing (e.g., "nursing", "pharmacy", "social-work"). */
  readonly category: string;

  /** User ID of the person assigned to this task. */
  readonly assignedTo: string;

  /** Team responsible for this task. */
  readonly assignedTeam: string;

  /** User or system that created this task. */
  readonly createdBy: string;

  /** ISO-8601 creation timestamp. */
  readonly createdAt: string;

  /** ISO-8601 last update timestamp. */
  readonly updatedAt: string;

  /** ISO-8601 due date, null if no deadline. */
  readonly dueDate: string | null;

  /** ISO-8601 completion timestamp, null if not completed. */
  readonly completedAt: string | null;

  /** SLA target in minutes from creation, null if no SLA. */
  readonly slaMinutes: number | null;

  /** Whether the task has exceeded its SLA or due date. */
  readonly isOverdue: boolean;

  /** Parent task ID for hierarchical task decomposition. */
  readonly parentTaskId: string | null;

  /** Extensible metadata for integration-specific data. */
  readonly metadata: Readonly<Record<string, unknown>>;

  /** Full audit trail of actions taken on this task. */
  readonly auditTrail: ReadonlyArray<TaskAuditEntry>;
}

/**
 * Filter criteria for querying tasks.
 */
export interface TaskFilter {
  readonly status?: ReadonlyArray<TaskStatus>;
  readonly priority?: ReadonlyArray<TaskPriority>;
  readonly assignedTo?: string;
  readonly assignedTeam?: string;
  readonly category?: string;
  readonly patientId?: string;
  readonly encounterId?: string;
  readonly source?: TaskSource;
  readonly isOverdue?: boolean;
  readonly parentTaskId?: string | null;
  readonly createdAfter?: string;
  readonly createdBefore?: string;
}

/**
 * Summary statistics for a user's or team's task inbox.
 */
export interface TaskInboxSummary {
  /** Total tasks in the inbox. */
  readonly totalTasks: number;

  /** Tasks in pending status. */
  readonly pendingCount: number;

  /** Tasks in in-progress status. */
  readonly inProgressCount: number;

  /** Tasks that are overdue. */
  readonly overdueCount: number;

  /** Tasks in escalated status. */
  readonly escalatedCount: number;

  /** Breakdown by priority. */
  readonly byPriority: Readonly<Record<TaskPriority, number>>;

  /** Breakdown by category. */
  readonly byCategory: Readonly<Record<string, number>>;

  /** ISO-8601 timestamp when this summary was computed. */
  readonly computedAt: string;
}

/**
 * Determine if a task is overdue based on its due date or SLA.
 */
export function isTaskOverdue(task: Task): boolean {
  if (task.status === 'completed' || task.status === 'cancelled') {
    return false;
  }

  const now = Date.now();

  if (task.dueDate) {
    return new Date(task.dueDate).getTime() < now;
  }

  if (task.slaMinutes !== null) {
    const slaDeadline = new Date(task.createdAt).getTime() + task.slaMinutes * 60 * 1000;
    return slaDeadline < now;
  }

  return false;
}

/**
 * Priority weight for sorting tasks. Higher weight = more urgent.
 */
export const TASK_PRIORITY_WEIGHT: Readonly<Record<TaskPriority, number>> = {
  urgent: 4,
  high: 3,
  medium: 2,
  low: 1,
};

/**
 * Sort tasks by priority (urgent first), then by overdue status, then by creation date.
 */
export function sortTasksByUrgency(tasks: ReadonlyArray<Task>): ReadonlyArray<Task> {
  return [...tasks].sort((a, b) => {
    // Overdue tasks first
    if (a.isOverdue !== b.isOverdue) {
      return a.isOverdue ? -1 : 1;
    }

    // Then by priority weight (descending)
    const weightDiff = TASK_PRIORITY_WEIGHT[b.priority] - TASK_PRIORITY_WEIGHT[a.priority];
    if (weightDiff !== 0) return weightDiff;

    // Then by creation date (oldest first)
    return new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime();
  });
}
