/**
 * Cron run history + findings store (file-backed).
 *
 * Storage: VELYA_CRON_PATH or /data/velya-cron/cron.json
 *
 * Shape:
 *   {
 *     runs: [
 *       { id, jobId, startedAt, finishedAt, status, durationMs, summary, findingsCount }
 *     ],
 *     findings: [
 *       {
 *         id, jobId, runId, severity, surface, target, message, suggestion?,
 *         shadowAction?, status, createdAt, resolvedAt?, resolvedBy?, resolutionNote?
 *       }
 *     ],
 *     learnings: [
 *       { id, finding patternId, observed, recommendation, learnedAt }
 *     ]
 *   }
 *
 * "shadow-mode" findings carry a `shadowAction` (the action the agent WOULD
 * have taken if it were running in active mode). They are NEVER auto-applied
 * — a human reviews and either dismisses or "promotes" the finding to
 * trigger the action manually. This satisfies .claude/rules/agents.md:
 *
 *   "Every agent must run in shadow mode before production activation."
 *   "No autonomous agents without human oversight for clinical or
 *    financial decisions."
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import { randomBytes } from 'crypto';
import { audit } from './audit-logger';

const STORAGE_PATH = process.env.VELYA_CRON_PATH || '/data/velya-cron/cron.json';
const MAX_RUNS = 500;
const MAX_FINDINGS = 1000;
const MAX_LEARNINGS = 500;

export type Severity = 'info' | 'low' | 'medium' | 'high' | 'critical';

export type Surface =
  | 'frontend.route'
  | 'frontend.component'
  | 'backend.api'
  | 'backend.auth'
  | 'backend.audit-chain'
  | 'data.fixture'
  | 'data.referential'
  | 'data.duplication'
  | 'infra.k8s'
  | 'infra.tls'
  | 'infra.disk'
  | 'security.headers'
  | 'security.rate-limit'
  | 'compliance.contrast'
  | 'compliance.field-link'
  | 'function.permission'
  | 'function.role-mapping';

export type FindingStatus =
  | 'new'
  | 'shadow-recommendation-ready'
  | 'in-review'
  | 'resolved-auto'
  | 'resolved-manual'
  | 'dismissed';

export type RunStatus = 'running' | 'success' | 'partial' | 'failed';

export interface CronRun {
  id: string;
  jobId: string;
  startedAt: string;
  finishedAt?: string;
  status: RunStatus;
  durationMs?: number;
  summary?: string;
  findingsCount: number;
  errorMessage?: string;
}

export interface CronFinding {
  id: string;
  jobId: string;
  runId: string;
  severity: Severity;
  surface: Surface;
  /** What the finding is about (e.g. route path, file path, fixture id) */
  target: string;
  /** Plain-language description in PT-BR */
  message: string;
  /** Optional structured details */
  details?: Record<string, unknown>;
  /** Recommendation generated by the agent loop (shadow mode) */
  suggestion?: string;
  /** The action the agent WOULD take if active mode were enabled */
  shadowAction?: { type: string; payload?: Record<string, unknown> };
  status: FindingStatus;
  createdAt: string;
  resolvedAt?: string;
  resolvedBy?: string;
  resolutionNote?: string;
}

export interface AgentLearning {
  id: string;
  patternId: string;
  observation: string;
  recommendation: string;
  occurrences: number;
  firstSeenAt: string;
  lastSeenAt: string;
}

interface StoreShape {
  runs: CronRun[];
  findings: CronFinding[];
  learnings: AgentLearning[];
}

function ensureStorage(): void {
  const dir = dirname(STORAGE_PATH);
  if (!existsSync(dir)) {
    try {
      mkdirSync(dir, { recursive: true });
    } catch {
      // ignore
    }
  }
  if (!existsSync(STORAGE_PATH)) {
    try {
      writeFileSync(
        STORAGE_PATH,
        JSON.stringify({ runs: [], findings: [], learnings: [] }, null, 2),
      );
    } catch {
      // ignore
    }
  }
}

function readStore(): StoreShape {
  ensureStorage();
  try {
    const raw = readFileSync(STORAGE_PATH, 'utf8');
    const parsed = JSON.parse(raw) as StoreShape;
    return {
      runs: parsed.runs ?? [],
      findings: parsed.findings ?? [],
      learnings: parsed.learnings ?? [],
    };
  } catch {
    return { runs: [], findings: [], learnings: [] };
  }
}

function writeStore(store: StoreShape): void {
  ensureStorage();
  try {
    writeFileSync(STORAGE_PATH, JSON.stringify(store, null, 2));
  } catch {
    // best effort
  }
}

export function startRun(jobId: string): CronRun {
  const run: CronRun = {
    id: `RUN-${Date.now().toString(36)}-${randomBytes(2).toString('hex')}`,
    jobId,
    startedAt: new Date().toISOString(),
    status: 'running',
    findingsCount: 0,
  };
  const store = readStore();
  store.runs.unshift(run);
  store.runs = store.runs.slice(0, MAX_RUNS);
  writeStore(store);
  return run;
}

export function finishRun(
  runId: string,
  status: RunStatus,
  summary: string,
  errorMessage?: string,
): CronRun | null {
  const store = readStore();
  const idx = store.runs.findIndex((r) => r.id === runId);
  if (idx === -1) return null;
  const run = store.runs[idx];
  run.finishedAt = new Date().toISOString();
  run.status = status;
  run.summary = summary;
  run.errorMessage = errorMessage;
  run.durationMs = new Date(run.finishedAt).getTime() - new Date(run.startedAt).getTime();
  store.runs[idx] = run;
  writeStore(store);

  audit({
    category: 'system',
    action: `cron.${status}`,
    description: `Cron job ${run.jobId} terminou com status ${status}: ${summary}`,
    actor: 'cron-scheduler',
    resource: `cron-job:${run.jobId}`,
    result: status === 'success' ? 'success' : status === 'failed' ? 'error' : 'warning',
    details: { runId, durationMs: run.durationMs, findingsCount: run.findingsCount },
  });

  return run;
}

export interface CreateFindingInput {
  jobId: string;
  runId: string;
  severity: Severity;
  surface: Surface;
  target: string;
  message: string;
  details?: Record<string, unknown>;
  shadowAction?: { type: string; payload?: Record<string, unknown> };
}

export function createFinding(input: CreateFindingInput): CronFinding {
  const finding: CronFinding = {
    id: `FND-${Date.now().toString(36)}-${randomBytes(2).toString('hex')}`,
    ...input,
    status: 'new',
    createdAt: new Date().toISOString(),
  };
  const store = readStore();
  // Increment findings count on the run
  const runIdx = store.runs.findIndex((r) => r.id === input.runId);
  if (runIdx >= 0) store.runs[runIdx].findingsCount += 1;
  store.findings.unshift(finding);
  store.findings = store.findings.slice(0, MAX_FINDINGS);
  writeStore(store);
  return finding;
}

export function listRuns(opts: { jobId?: string; limit?: number } = {}): CronRun[] {
  const store = readStore();
  return store.runs.filter((r) => !opts.jobId || r.jobId === opts.jobId).slice(0, opts.limit ?? 50);
}

export function listFindings(
  opts: {
    jobId?: string;
    status?: FindingStatus;
    severity?: Severity;
    surface?: Surface;
    limit?: number;
  } = {},
): CronFinding[] {
  const store = readStore();
  return store.findings
    .filter((f) => {
      if (opts.jobId && f.jobId !== opts.jobId) return false;
      if (opts.status && f.status !== opts.status) return false;
      if (opts.severity && f.severity !== opts.severity) return false;
      if (opts.surface && f.surface !== opts.surface) return false;
      return true;
    })
    .slice(0, opts.limit ?? 100);
}

export function getFinding(id: string): CronFinding | null {
  const store = readStore();
  return store.findings.find((f) => f.id === id) ?? null;
}

export function updateFinding(
  id: string,
  patch: Partial<Omit<CronFinding, 'id' | 'jobId' | 'runId' | 'createdAt'>>,
  actor?: string,
): CronFinding | null {
  const store = readStore();
  const idx = store.findings.findIndex((f) => f.id === id);
  if (idx === -1) return null;
  const before = store.findings[idx];
  const next: CronFinding = { ...before, ...patch };
  if (patch.status && patch.status !== before.status && actor) {
    next.resolvedBy = actor;
    next.resolvedAt = new Date().toISOString();
  }
  store.findings[idx] = next;
  writeStore(store);

  audit({
    category: 'system',
    action: 'cron.finding-updated',
    description: `Finding ${id} → ${patch.status ?? 'updated'}`,
    actor: actor ?? 'system',
    resource: `cron-finding:${id}`,
    result: 'info',
    details: { from: before.status, to: patch.status, fields: Object.keys(patch) },
  });

  return next;
}

export function recordLearning(input: {
  patternId: string;
  observation: string;
  recommendation: string;
}): AgentLearning {
  const store = readStore();
  const existing = store.learnings.find((l) => l.patternId === input.patternId);
  const now = new Date().toISOString();
  if (existing) {
    existing.occurrences += 1;
    existing.lastSeenAt = now;
    existing.observation = input.observation;
    existing.recommendation = input.recommendation;
    writeStore(store);
    return existing;
  }
  const learning: AgentLearning = {
    id: `LRN-${Date.now().toString(36)}-${randomBytes(2).toString('hex')}`,
    patternId: input.patternId,
    observation: input.observation,
    recommendation: input.recommendation,
    occurrences: 1,
    firstSeenAt: now,
    lastSeenAt: now,
  };
  store.learnings.unshift(learning);
  store.learnings = store.learnings.slice(0, MAX_LEARNINGS);
  writeStore(store);
  return learning;
}

export function listLearnings(limit = 50): AgentLearning[] {
  const store = readStore();
  return store.learnings.slice(0, limit);
}
